Repository ChustaSoft/CommonNET, pull requests merged in 2020-05, with the labels that each got.

#38 [WPF] : Version 1.0.0 : CommonNET WPF library created
  ChustaSoft.Common.WPF/Base/TraceableViewModelBase.cs
  ChustaSoft.Common.WPF/Base/ViewModelBase.cs
  ChustaSoft.Common.WPF/ChustaSoft.Common.WPF.csproj
  ChustaSoft.Common.WPF/Controls/MultiSelection.xaml
  ChustaSoft.Common.WPF/Controls/MultiSelection.xaml.cs
  ChustaSoft.Common.WPF/Controls/Selection.xaml
  ChustaSoft.Common.WPF/Controls/Selection.xaml.cs
  ChustaSoft.Common.WPF/Helpers/DefaultVisibilityConverter.cs
  ChustaSoft.Common.WPF/Helpers/RelayCommand.cs
  ChustaSoft.Common.WPF/Helpers/VisibilityConverter.cs
  ChustaSoft.Common.WPF/Models/SelectableOption.cs
  ChustaSoft.CommonNET.sln
Labels: deploy

#45 [WPF]: Version 1.0.1 -> SelectableOption generic
  ChustaSoft.Common.WPF/ChustaSoft.Common.WPF.csproj
  ChustaSoft.Common.WPF/Models/SelectableOption.cs
Labels: deploy

#46 [WPF]: Version 1.0.2 -> SelectableOption generic functional fix
  ChustaSoft.Common.WPF/ChustaSoft.Common.WPF.csproj
  ChustaSoft.Common.WPF/Models/SelectableOption.cs
Labels: deploy, invalid

#48 Documentation improved across the entire project
  ChustaSoft.Common.AspNet.UnitTest/BaseTests/ApiControllerBaseTest.cs
  ChustaSoft.Common.AspNet.UnitTest/ChustaSoft.Common.AspNet.UnitTest.csproj
  ChustaSoft.Common.AspNet/Base/ApiControllerBase.cs
  ChustaSoft.Common.AspNet/ChustaSoft.Common.AspNet.csproj
  ChustaSoft.Common.WPF/Base/TraceableViewModelBase.cs
  ChustaSoft.Common.WPF/Base/ViewModelBase.cs
  ChustaSoft.Common.WPF/ChustaSoft.Common.WPF.csproj
  ChustaSoft.Common.WPF/Helpers/DefaultVisibilityConverter.cs
  ChustaSoft.Common.WPF/Helpers/RelayCommand.cs
  ChustaSoft.Common.WPF/Helpers/VisibilityConverter.cs
  ChustaSoft.Common.Wpf.UnitTest/BaseTests/ViewModelBaseTest.cs
  ChustaSoft.Common.Wpf.UnitTest/ChustaSoft.Common.Wpf.UnitTest.csproj
  ChustaSoft.Common.Wpf.UnitTest/HelperTests/DefaultVisibilityConverterUnitTest.cs
  ChustaSoft.Common.Wpf.UnitTest/HelperTests/SelectableOptionExtensionsUnitTest.cs
  ChustaSoft.Common.Wpf.UnitTest/HelperTests/VisibilityConverterUnitTest.cs
  ChustaSoft.Common/ChustaSoft.Common.csproj
  ChustaSoft.CommonNET.sln
  README.md
Labels: documentation, maintenance

#49 [WPF]: Version 1.1.0 -> Loading control
  ChustaSoft.Common.WPF/ChustaSoft.Common.WPF.csproj
  ChustaSoft.Common.WPF/Controls/Loading.xaml
  ChustaSoft.Common.WPF/Controls/Loading.xaml.cs
Labels: deploy

#50 [WPF]: Version 1.1.1 -> Loading control fix
  ChustaSoft.Common.WPF/ChustaSoft.Common.WPF.csproj
  ChustaSoft.Common.WPF/Controls/Loading.xaml
Labels: deploy

#52 [WPF]: Version 1.2.0 -> Improved loading configuration
  ChustaSoft.Common.WPF/ChustaSoft.Common.WPF.csproj
  ChustaSoft.Common.WPF/Controls/Loading.xaml
  ChustaSoft.Common.WPF/Controls/Loading.xaml.cs
  ChustaSoft.Common.WPF/Controls/LoadingPosition.cs
  ChustaSoft.Common.WPF/Controls/LoadingPositionConverter.cs
  ChustaSoft.Common.WPF/Controls/LoadingType.cs
  ChustaSoft.Common.WPF/Helpers/VisibilityConverter.cs
  ChustaSoft.Common.Wpf.UnitTest/HelperTests/VisibilityConverterUnitTest.cs
Labels: deploy
